project:
  type: book

book:
  title: "Data mining algorithm"
  author: "Youngrok Lee, Jong-Seok Lee"
  date: today
  chapters:
    - index.qmd
    - ch02_regression.qmd
    - ch03_regularized_regression.qmd
    - ch04_dimension_reduction.qmd
    - ch06_logistic_regression.qmd

number-sections: false

format:
  html:
    theme: cosmo



